#!/bin/bash

echo creating database $dbname
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='CREATE DATABASE $dbname;'"

echo creating user $dbuser
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='CREATE USER '$dbuser'@'localhost' IDENTIFIED BY '$dbpass';'"

echo assigning privileges for user $dbuser to database $dbname
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='GRANT ALL ON $dbname.* TO '$dbuser'@'localhost' IDENTIFIED BY '$dbpass' WITH GRANT OPTION;'"

echo flushing privileges
docker exec -it mariadb /bin/bash -c "mysql --user='root' --password='$dbrootpass' --execute='FLUSH PRIVILEGES;'"
