#!/bin/bash

echo This will install sendmail and use a gmail account as a relay for outgoing emails
read -p "press enter to continue"

echo what is your office365 email address?: ; read office365_email_address
echo what is your office365 email password?: ; read office365_password
echo where should we send a test email?: ; read recipient

echo installing sendmail
apt install -y sendmail sasl2-bin mailutils sendmail-bin openssl > /dev/null 2>&1

echo configuring sendmail
mkdir -m 700 /etc/mail/authinfo/
echo AuthInfo: \"U:root\" \"I:$office365_email_address\" \"P:$office365_password\" >> /etc/mail/authinfo/gmail-auth
makemap hash /etc/mail/authinfo/ofice365-auth < /etc/mail/authinfo/office365-auth

sed -i '/MAILER_DEFINITIONS/idefine(`SMART_HOST'\'',`[smtp.office365.com]'\'')dnl' /etc/mail/sendmail.mc
sed -i '/MAILER_DEFINITIONS/idefine(`RELAY_MAILER_ARGS'\'', `TCP $h 587'\'')dnl' /etc/mail/sendmail.mc
sed -i '/MAILER_DEFINITIONS/idefine(`ESMTP_MAILER_ARGS'\'', `TCP $h 587'\'')dnl' /etc/mail/sendmail.mc
sed -i '/MAILER_DEFINITIONS/idefine(`confAUTH_OPTIONS'\'', `A p'\'')dnl' /etc/mail/sendmail.mc
sed -i '/MAILER_DEFINITIONS/iTRUST_AUTH_MECH(`EXTERNAL DIGEST-MD5 CRAM-MD5 LOGIN PLAIN'\'')dnl' /etc/mail/sendmail.mc
sed -i '/MAILER_DEFINITIONS/idefine(`confAUTH_MECHANISMS'\'', `EXTERNAL GSSAPI DIGEST-MD5 CRAM-MD5 LOGIN PLAIN'\'')dnl' /etc/mail/sendmail.mc
sed -i '/MAILER_DEFINITIONS/iFEATURE(`authinfo'\'',`hash -o /etc/mail/authinfo/office365-auth.db'\'')dnl' /etc/mail/sendmail.mc

make -C /etc/mail > /dev/null 2>&1
/etc/init.d/sendmail reload

echo sending test email
echo "Just testing my sendmail office365 relay" | mail -s "Sendmail office365 Relay" $recipient
