#!/bin/bash

echo securing mariadb
mysql --user="root" --password="" --execute="SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password_here');"
mysql --user="root" --password="" --execute="DELETE FROM mysql.user WHERE User='';"
mysql --user="root" --password="" --execute="DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
mysql --user="root" --password="" --execute="DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';"
mysql --user="root" --password="" --execute="FLUSH PRIVILEGES;"
